/// Flutter icons Fireicon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fireicon
///      fonts:
///       - asset: fonts/Fireicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Fireicon {
  Fireicon._();

  static const _kFontFam = 'Fireicon';
  static const String? _kFontPkg = null;

  static const IconData vectorflake_svg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vectorfire = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
